### ISSUE TITLE
TyUpdater 0.9.3 can't be opened on macOS

### ISSUE THREAD

**Issue by 2xAA** [Koromix/tytools#70]
Tested on macOS 10.14 and macOS 11 - both have the same error.

TyUpdater 0.9.2 works perfectly.

![Screenshot 2021-01-12 at 09 10 53](https://user-images.githubusercontent.com/554219/104293636-1d763800-54b6-11eb-8ff4-53d6a711703a.png)

**Comment by Koromix** [comment]
Weird.. I'll try it today, though I only have El Capitan here (Macbook is from 2009), and look for what differs between 0.9.2 and 0.9.3.

**Comment by Koromix** [comment]
Yeah, I should have noticed the problem when I made the release... The dmg file is ten times smaller than the one of 0.9.2. That's because I made the mistake of building with a non-static build of Qt.

I'm rebuilding Qt and then TyTools, it should be ok in a few hours (MacBook from 2009, HDD... it's slow).

**Comment by Koromix** [comment]
I've replaced the DMG with a working one, thanks!
